name: Calling Custom Action
on: [workflow_dispatch]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        id: hello-action
        uses: anotherRedbeard/hello-world-docker-action@v1
        with:
          who-to-greet: '@octocat'
      - name: Output time set in the container
        run: echo "The time was ${{ steps.hello-action.outputs.time }} when the action said hello"
