name: GitHub Actions Demo

on: 
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Triggering event:  ${{ github.event_name }}"
          echo "Current branch is ${{ github.ref }}"

      - uses: actions/checkout@v3.3.0

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
  Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: Test
    steps:
      - run: |
          echo ":bug: Testing..."
  Load-Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: Load-Test
    steps:
      - run: |
          echo ":bug: Testing..."
          sleep 15
  Production:
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'Production'
    needs: [Test, Load-Test]
    environment: 
      name: Production
      url: https://writeabout.net
    steps:
      - run: |
          echo ":airplane: Step 1 deploying..."
          sleep 10

      - run: |
          echo ":airplane: Step 1 deploying..."
          sleep 10

      - run: |
          echo ":airplane: Step 1 deploying..."
          sleep 10

      - run: |
          echo ":airplane: Step 1 deploying..."
          sleep 10

      - run: |
          echo ":airplane: Step 1 deploying..."
          sleep 10
