name: DEmo Test Environment

on: [workflow_dispatch]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Triggering event: ${{ github_event_name }}
          sleep 15
  Production:
    runs-on: ubuntu-latest
    needs: [Build]
    environment:
      name: Prod-2
      url: https://writeabout.net
    steps:
      - run: |
          echo "Production!"
          
